version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    branches:
        only:
          - master
    steps:



      # git get
      - run: apk update && apk add git
      
      # blogリポジトリのデータを取得する
      - run: mkdir chk
      - checkout: 
          path: chk
      
      # hugoでTIL作る
      - run: hugo new site TIL

      # TIL内にgitリポジトリ作り、テーマを拾ってくる
      - run:
          command: git init
          working_directory: TIL
      - run:
          command: git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
          working_directory: TIL
      - run:
          command: echo 'theme = "ananke"' >> TIL/config.toml 

      

      # ビルドしてユーザページサイトにPushする
      - deploy:
          command: |    
              
              git config --global user.email "mi.ki.ri.hassha.p@gmail.com"
              git config --global user.name "mi-ki-ri"
              git init
              
              rm -rf ./*

              git remote add origin https://github.com/mi-ki-ri/TIL-Web.git
              git add .
              git commit -m "CircleCI"
              git pull origin master --allow-unrelated-histories --no-edit
              rm -rf ./*
            

              mv -f ../chk ../TIL/content
              hugo

              mv -f ./public/* ../TIL

              git push -u origin master
          working_directory: TIL