version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:




      - run: apk update && apk add git
      
      
      # blogリポジトリのデータを取得する
      - run: mkdir $HOME/src
      - run: cd $HOME/src
      - checkout
      
      - run: ls
      
      # hugo持ってくる
      - run: hugo new site TIL

    
      - run: git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
      - run: mv -f themes TIL
      - run: echo 'theme = "ananke"' >> TIL/config.toml 

      - run: mv -f content TIL/content

      - run: ls -a

      - run: cd TIL

      - run: ls -a

      # ビルドする
      - run: TIL/hugo

      # ユーザページサイトにPushする
      - deploy:
          command: git subtree push --prefix public origin gh-pages