version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:




      - run: apk update && apk add git
      
      
      # blogリポジトリのデータを取得する
      - run: mkdir $HOME/src
      - run: cd $HOME/src
      - checkout
      
      - run: ls
      
      # hugo持ってくる
      - run: hugo new site TIL
      - run: cd TIL

    
      - run: git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
      - run: echo 'theme = "ananke"' >> config.toml 

      - run: cd ../
      - run: cp -r circleci TIL/content
      - run: cd TIL

      # ビルドする
      - run: hugo

      # ユーザページサイトにPushする
      - deploy:
          command: git subtree push --prefix public origin gh-pages