version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - run: apk update && apk add git
      # hugo持ってくる
      - run: mkdir $HOME/src
      - run: cd $HOME/src
      - run: hugo new site TIL
      - run: cd TIL
      - run: git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
      - run: echo 'theme = "ananke"' >> config.toml 

      # blogリポジトリのデータを取得する
      - checkout

      - run: cp -r working_directory content


      # ビルドする
      - run: hugo

      # ユーザページサイトにPushする
      - deploy:
          command: git subtree push --prefix public origin gh-pages