version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:

      # hugo持ってくる
      - run: mkdir $HOME/src
      - run: cd $HOME/src
      - run: git clone https://github.com/gohugoio/hugo.git
      - run: cd hugo
      - run: go install --tags extended
      - run: git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke


      # blogリポジトリのデータを取得する
      - checkout

      - run: cp -r working_directory hugo/content


      # ビルドする
      - run: hugo

      # ユーザページサイトにPushする
      - deploy:
          command: 