version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:




      - run: apk update && apk add git
      
      # git subtree持ってくる
      - run: mkdir src
      - run: 
          command: git clone https://github.com/git/git.git
          working_directory: src
      - run: 
          command: |
              make
              install -m 755 git-subtree /usr/lib/git-core
          working_directory: src/git/contrib/subtree 


      # blogリポジトリのデータを取得する
      - run: mkdir chk
      - checkout: 
          path: chk
      
      - run: ls
      
      # hugo持ってくる
      - run: hugo new site TIL

    
      - run:
          command: git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
          working_directory: TIL
      - run: echo 'theme = "ananke"' >> TIL/config.toml 

      - run: mv -f chk/content TIL/content

      - run: ls -a

      # ビルドする
      - run: 
          command: hugo
          working_directory: TIL

      # ユーザページサイトにPushする
      - deploy:
          command: git subtree push --prefix TIL/public origin gh-pages
          working_directory: TIL/public